workflows:
  ios-production:
    name: PluhykBloomora iOS Production
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    integrations:
      app_store_connect: Pluhyk Bloomora
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.rup.pl7n5kbl00m
      
      vars:
        BUNDLE_ID: "com.rup.pl7n5kbl00m"
        APP_STORE_APPLE_ID: 6758214455
        XCODE_PROJECT: "PluhykBloomora.xcodeproj"
        XCODE_SCHEME: "PluhykBloomora"
      
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'master'
          include: true
          source: true
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID") + 1))
      
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      email:
        recipients:
          - devs@unnamedtm.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testing
        expire_build_submitted_for_review: true
        submit_to_app_store: false
